_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 6
epoch:
    value: 1
lr:
    value: 0.001
max_len:
    value: 1024
size:
    value: default
ssmax:
    value: true
use_pos_enc:
    value: false
wandb:
    value: true
